# -*- coding: utf-8 -*-
"""PCA1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_RZpvRpnzb88PRnclXixW01xIHFSoo2q
"""

import pandas as pd
import numpy as np
from sklearn import datasets

dataset = datasets.load_breast_cancer()

dataset.keys()

dataset["feature_names"]

X = pd.DataFrame(dataset["data"], columns=dataset["feature_names"])

X.head()

y = pd.DataFrame(data=dataset["target"],columns=["Target"])
y = y['Target']
y

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_scaled.shape

from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

n_components = [5,10,15,20,25,30]
for i in n_components:
  pca = PCA(n_components=i)
  X_pca = pca.fit_transform(X_scaled)
  X_train, X_test, y_train, y_test = train_test_split(X_pca,y,test_size=.2)
  model = LogisticRegression()
  model.fit(X_train, y_train)
  print(f"the accuracy for {i} principle component: ",(model.score(X_test,y_test)))

import pandas as pd
from sklearn import datasets

dataset = datasets.load_breast_cancer()
dataset.keys()

X = pd.DataFrame(dataset["data"],columns=dataset["feature_names"])
y = pd.DataFrame(dataset["target"],columns=["target"])
X.head()

print(X.shape)
print(y.shape)

y.head()

y = y["target"]

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_scaled

from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
components = [5,10,15,20,25,30]
for i in components:
  pca = PCA(n_components=i)
  X_pca = pca.fit_transform(X_scaled)
  X_train, X_test, y_train, y_test = train_test_split(X_pca,y,test_size=0.2)
  model = LogisticRegression()
  model.fit(X_train,y_train)
  print(f"the accuracy of {i} principle components is ",(model.score(X_test,y_test)))

from sklearn import datasets
import pandas as pd

dataset = datasets.load_breast_cancer()
dataset.keys()

X = pd.DataFrame(dataset["data"],columns=dataset["feature_names"])

X.head()

y =pd.DataFrame(dataset["target"], columns=["Target"])
y =

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_scaled

from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import f1_score
components = [5,10,15,20,25,30]
for i in components:
  pca = PCA(n_components=i)
  X_pca = pca.fit_transform(X_scaled)
  X_train, X_test, y_train, y_test = train_test_split(X_pca,y,test_size=0.2)
  model = SVC(kernel="rbf", gamma ="auto")
  model.fit(X_train, y_train)
  y_pred = model.predict(X_test)
  print(f"F1 score of {i} principle components : ",f1_score(y_test,y_pred))

